# Generated by Django 5.1 on 2024-08-23 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cellphone", models.CharField(max_length=15)),
                ("payment", models.IntegerField()),
            ],
        ),
    ]
